imports:
    - { resource: parameters.yml }

framework:
    #esi:             ~
    translator:      { fallback: fr_FR }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
        engines:
            - twig
        #assets_version: SomeVersionScheme
        assets_base_urls:
            http:                 []
            ssl:                  []
    default_locale:  %locale%
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:
        handler_id: session.handler.pdo

parameters:
    pdo.db_options:
        db_table: session
        db_id_col: session_id
        db_data_col: session_value
        db_time_col: session_time
    paths:
        storage:
            main:    '../storage/'
            avatar:  'avatar/'
            advert:  'advert/'
            sport:   '../storage/sports/'
            tmp:     '../storage/tmp/'
        cache:
            main:    '../cache/'
            avatar:  '../cache/avatar/'
            advert:  '../cache/advert/'
            sport:   '../cache/sports/'

    social:
        twitter:
            consumer_key:        'HiDIkFneiV1o96XGi9clA'
            consumer_secret:     '1IGKJpQwBiTjAVmu766OBGekGzuWfRkkRmnbgRFDdY'
        facebook:
            #production app
            #application_id:      '125838870904986'
            #application_secret:  '292e9ca79478e5542614a20c8be29550'
            #devel app
            application_id:      '167823653374329'
            application_secret:  'f71fecdbb5f5c61a562caedb633dd802'
            scope:               'email,user_about_me,user_interests,user_location,publish_stream,read_friendlists'
        google:
            client_id:           '301572749715.apps.googleusercontent.com'
            client_secret:       'JakNGT0649JERi7Dg7np2v-B'
            developer_key:       'Kj89kdljsj43ius3349djlkds'
            app_name:            'RigBag by ProtonLabs Ltd.'

    paypal:
        #username:                'maciek_1356234351_biz_api1.protonlabs.co'
        #password:                '1356234383'
        #signature:               'AFcWxV21C7fd0v3bYYYRCpSSRl31AOJx9Fb0GjgHzq5th3xBO9Eb3.6w'
        #end_point:               'https://api-3t.sandbox.paypal.com/nvp'
        #ap_end_point:            'https://svcs.sandbox.paypal.com/AdaptivePayments'
        #ap_wsdl:                 'https://svcs.sandbox.paypal.com/AdaptivePayments?wsdl'
        #application_id:          'APP-80W284485P519543T'
        #paypal_url:              'https://www.sandbox.paypal.com/webscr'
        
        username:                'randall_api1.rigbag.com'
        password:                '2LK42XCQEYDNELTS'
        signature:               'AFcWxV21C7fd0v3bYYYRCpSSRl31A-021-gk6zJAYSwWC5VM3yb-KZIo'
        application_id:          'APP-83362811C57021258'
        end_point:               'https://api-3t.paypal.com/nvp'
        ap_end_point:            'https://svcs.paypal.com/AdaptivePayments'
        ap_wsdl:                 'https://svcs.paypal.com/AdaptivePayments?wsdl'
        paypal_url:              'https://www.paypal.com/cgi-bin/webscr'

    azure:
        storage:
            protocol:            'http'
            account:             'rigbagmedia'
            primaryKey:          'OOyeVolC5nH6Rcp3H5oNPaFXmSAbGVpW3Xuz6W8wd4ekq837VdvqWbIqQWy5hdXCW3XAGzcH4pz4Eli7lgzx3g=='
            secondaryKey:        'ds5A/6OAtf7bDub1WPoeiqA7k8NGkAiRQWatspQRC8ioqucKZI6oJfFAa9FzYZALMsb7yAlHCCkQyMSoOefOpQ=='
            container:           'media'
    azure.storage.url:                 'https://rigbagmedia.blob.core.windows.net/media/'

    prices:
       subscription_annual:      '30'
       advert_add:               '5'

services:
    pdo:
        class: PDO
        arguments:
            dsn: "mysql:host=%database_host%;dbname=%database_name%"
            user: %database_user%
            password: %database_password%
    session.handler.pdo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: [@pdo, %pdo.db_options%]
    rigbag.auth.action_listener:
        class: Proton\RigbagBundle\EventListener\AuthListener
        arguments: []
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    text.twig.extension:
        class: Twig_Extensions_Extension_Text
        tags:
            -  { name: twig.extension }
    cache:
        class: Doctrine\Common\Cache\ApcCache

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        mediaUrl:         %azure.storage.url%
    form:
        resources:
            - 'ProtonRigbagBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    #debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    java: /usr/bin/java
    #java: c:\\Program Files\\Java\\jre6\\bin\\java.exe
    filters:
        less:
            node: /usr/bin/nodejs
            node_paths: [/usr/lib/node_modules/less,/usr/lib/node_modules,.npm/less/1.3.3/package/bin/, /usr/lib/node_modules/less, /usr/lib/node_modules/less/bin]
            #node: c:\\Program Files\\nodejs\\node.exe
            #node_paths: [c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules,C:\\Users\\Burned\\AppData\\Roaming\\npm,C:\\Users\\Burned\\AppData\\Roaming\\npm\\node_modules,C:\\Users\\Burned\\AppData\\Roaming\\npm\\node_modules\\less]
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    port:      %mailer_port%
    logging:   "%kernel.debug%"
    auth_mode: login
    spool:     { type: memory }